openapi: 3.0.0
info:
  title: Rezeptbuch API
  description: >
    The Rezeptbuch API provides endpoints to manage recipes, including listing, creating, downloading and updating recipes. 
    It also supports features such as filtering recipes, managing categories, and syncing data between clients and the server.
  version: 1.0.0
tags:
  - name: recipes
    description: Endpoints related to managing recipes
  - name: categories
    description: Endpoints related to managing recipe categories

paths:
  /list:
    get:
      tags:
        - recipes
      summary: List recipes
      description: Multiple filter/sort options can be specified in the parameters
      parameters:
        - name: offset
          in: query
          description: How many recipes should be skipped
          required: false
          schema:
            type: integer
            default: 0
        - name: count
          in: query
          description: How many recipes should be returned
          required: true
          schema:
            type: integer
        - name: order_by
          in: query
          description: What the recipes should be ordered by
          required: false
          schema:
            type: string
            default: title
            enum:
              - title
              - cooking_time
        - name: order
          in: query
          description: What direction the order should have
          required: false
          schema:
            type: string
            default: asc
            enum:
              - asc
              - desc
        - name: categories
          in: query
          description: Which categories should be included (if none are specified dont filter by categories)
          required: false
          schema:
            type: array
            items: 
              type: string
      responses:
        '200':
          description: successful operation
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  recipes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Recipe'
        '400':
          description: Bad Request (e.g. value for order_by not title or cooking_time)
                  
components:
  schemas:
    Recipe:
      type: object
      properties:
        offset:
          type: integer
          format: int64
          example: 30
        count:
          type: integer
          format: int64
          example: 15
