openapi: 3.0.0
info:
  title: Rezeptbuch API
  description: >
    The Rezeptbuch API provides endpoints to manage recipes, including listing, creating, downloading and updating recipes. 
    It also supports features such as filtering recipes, managing categories, and syncing data between clients and the server.
  version: 1.1.0
tags:
  - name: Recipes
    description: Endpoints related to recipes
  - name: Images
    description: Endpoints related to images
  - name: Categories
    description: Endpoints related to categories

paths:
  /recipes:
    get:
      tags:
        - Recipes
      summary: List recipes
      description: Multiple filter/sort options can be specified in the parameters
      parameters:
        - name: offset
          in: query
          description: How many recipes should be skipped
          required: false
          schema:
            type: integer
            default: 0
        - name: count
          in: query
          description: How many recipes should be returned (max 25)
          required: true
          schema:
            type: integer
            maximum: 25
        - name: order_by
          in: query
          description: What the recipes should be ordered by
          required: false
          schema:
            type: string
            default: title
            enum:
              - title
              - cooking_time
        - name: order
          in: query
          description: What direction the order should have
          required: false
          schema:
            type: string
            default: asc
            enum:
              - asc
              - desc
        - name: categories
          in: query
          description: Which categories should be included (if none are specified dont filter by categories)
          required: false
          schema:
            type: array
            items: 
              type: string
      responses:
        '200':
          description: successful operation
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  recipes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Recipe'
        '400':
          description: Bad Request (e.g. value for order_by not title or cooking_time)
    post:
      tags:
        - Recipes
      summary: Upload a recipe
      description: Endpoint to upload an XML file containing recipe data
      parameters:
        - name: uuid
          in: header
          description: UUID of the uploading user
          required: true
          schema:
            type: string
            example: 1caf616b-be5b-4769-8083-229c253e5005
      requestBody:
        content: 
          application/xml:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: successful upload
        '400':
          description: Bad request, e.g., malformed XML or validation error
          
  /recipes/{hash}:
    get:
      tags:
        - Recipes
      summary: Download a recipe
      description: Retrieve a recipe specified by a hash
      parameters:
        - name: hash
          in: path
          description: Hash of the recipe
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/xml:
              schema:
                type: string
                format: binary
        '404':
          description: Recipe not found (e.g. recipe with specified hash does not exist)
    put:
      tags:
        - Recipes
      summary: Update a recipe
      description: Endpoint to upload an XML file containing changed recipe data
      parameters:
        - name: hash
          in: path
          description: the hash under which the recipe was known before changing it
          required: true
          schema:
            type: string
            example: 36ec9bdaee807f2ae07f9f43c851ace40bad1e659f04f831704abe9d2efcf2df
        - name: uuid
          in: header
          description: UUID of the uploading user
          required: true
          schema:
            type: string
            example: 1caf616b-be5b-4769-8083-229c253e5005
      requestBody:
        content: 
          application/xml:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: successful update
        '400':
          description: Bad request, e.g., malformed XML, validation error or no recipe to be updated found

  /categories:
    get:
      tags:
        - Categories
      summary: List categories
      description: List of categories available to filter by
      parameters:
        - name: offset
          in: query
          description: How many recipes should be skipped
          required: false
          schema:
            type: integer
            default: 0
        - name: count
          in: query
          description: How many recipes should be returned (max 50)
          required: true
          schema:
            type: integer
            maximum: 50
      responses:
        '200':
          description: successful operation
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      type: string
        '400':
          description: no categories found
          
  /images/{hash}:
    get:
      tags:
        - Images
      summary: Download an image
      description: Retrieve an image specified by a hash referring to a recipe
      parameters:
        - name: hash
          in: path
          description: Hash of the recipe to which the image belongs
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
        '404':
          description: Image not found (e.g. recipe with specified hash does not exist or does not have an image)
    post:
      tags:
        - Images
      summary: Upload an image
      description: Endpoint to upload an image of a recipe
      parameters:
        - name: hash
          in: path
          description: Hash of the recipe to which the image belongs
          required: true
          schema:
            type: string
            example: 36ec9bdaee807f2ae07f9f43c851ace40bad1e659f04f831704abe9d2efcf2df
        - name: uuid
          in: header
          description: UUID of the uploading user
          required: true
          schema:
            type: string
            example: 1caf616b-be5b-4769-8083-229c253e5005
      requestBody:
        content: 
          image/png:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: successful upload
        '400':
          description: Bad request, e.g., recipe with given hash not found; wrong user
    put:
      tags:
        - Images
      summary: Update an image
      description: Endpoint to upload an image to change the image of a recipe
      parameters:
        - name: hash
          in: path
          description: Hash of the recipe to which the image belongs
          required: true
          schema:
            type: string
            example: 36ec9bdaee807f2ae07f9f43c851ace40bad1e659f04f831704abe9d2efcf2df
        - name: uuid
          in: header
          description: UUID of the uploading user
          required: true
          schema:
            type: string
            example: 1caf616b-be5b-4769-8083-229c253e5005
      requestBody:
        content: 
          image/png:
            schema:
              type: string
              format: binary
          image/jpeg:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: successful update
        '400':
          description: Bad request, e.g., recipe with given hash not found; wrong user      
          
          
components:
  schemas:
    Recipe:
      type: object
      properties:
        hash:
          type: string
          example: 36ec9bdaee807f2ae07f9f43c851ace40bad1e659f04f831704abe9d2efcf2df
        title:
          type: string
          example: Loco moco
        description:
          type: string
          example: A traditional Hawaiian dish consisting of rice, beef, gravy, and a sunny-side up fried egg.
        categories:
          type: array
          example: ["beef", "hawaiian"]
          items:
            type: string
        cooking_time:
          type: int
          example: 20
